### PR TITLE
Add brand neutral and free mic icon

### PR DESCRIPTION
**Pull request by DuyguKeskek**
Hello @OleksiyRudenko,
I added a brand neutral and a free mic icon that fits the design. 
Here is the screenshot : 
mic-icon

Thank you!

### CODE REVIEW

**Comment by DuyguKeskek** [comment]
This PR fixes #6 thanks!

**Comment by OleksiyRudenko** [comment]
@DuyguKeskek I am a bit confused as PR #7 contained commits for both icons.
Perhaps you created a new branch for the bell (`add-bell-icon`) not from `master` but from the branch with the mic icon in it (`add-mic`). That's why `add-bell-icon` branch contains commits for both icons.

Now, there is no much sense in merging this PR.

Just checked up. Yes, `add-bell-branch` contains commits from `add-icon`:
image

**Comment by DuyguKeskek** [comment]
@OleksiyRudenko You are right! Thanks for pointing it out.

**Comment by OleksiyRudenko** [comment]
Closing this PR for the changes to be introduced with it has been already introduced with #7 that is merge-rebased onto `master`.

**Pull request closed without merging**
